<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	 xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	 xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	 xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	 name="stiu">

	<xacro:property name="width" value=".2" />
	<xacro:property name="leglen" value=".6" />
	<xacro:property name="polelen" value=".2" />
	<xacro:property name="bodylen" value=".6" />
	<xacro:property name="baselen" value=".4" />
	<xacro:property name="wheeldiam" value=".065" />
	<xacro:property name="pi" value="3.1415" />

	<xacro:macro name="default_inertial" params="mass">
		<inertial>
      			<mass value="${mass}" />
		        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
			         iyy="1.0" iyz="0.0"
			         izz="1.0" />
		</inertial>
	</xacro:macro>

	<link name="base_link">
		<visual>
			<geometry>
				<box size = "0.174 0.11 0.06"/>
			</geometry>
			<material name="blue">
				<color rgba="0 0 .8 1"/>
			</material>
		</visual>
		<collision>
			<geometry>
				<box size = "0.174 0.11 0.06"/>
			</geometry>
		</collision>

		<xacro:default_inertial mass="10"/>
	</link>
	
	<xacro:macro name="wheel" params="prefix reflect">
		<link name="${prefix}_wheel">
			<visual>
				<geometry>
					<cylinder radius="${wheeldiam/2}" length=".03"/>
				</geometry>
				<material name="black">
					<color rgba="0 0 0 1"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<cylinder radius="${wheeldiam/2}" length=".03"/>
				</geometry>
			</collision>	
			<xacro:default_inertial mass="1"/>
		</link>
		<joint name="${prefix}_wheel_joint" type="continuous">
			<axis rpy="0 0 0" xyz="0 0 1"/>
			<parent link="base_link"/>
			<child link="${prefix}_wheel"/>
			<origin xyz="0 ${0.05*reflect} -0.03" rpy="${pi/2} 0 0"/>
      			<limit effort="100" velocity="100" />
			<joint_properties damping="0.0" friction="0.0" />

		</joint>

		<gazebo reference="${prefix}_wheel">
			<mu1 value="200.0"/>
			<mu2 value="100.0"/>
			<kp value="10000000.0"/>
			<kd value="1.0"/>
			<material>Gazebo/Grey</material>
		</gazebo>

		<gazebo>  
			<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
  			</plugin>
		</gazebo>
 
		<!-- This block connects the wheel joint to an actuator (motor), which informs both
    		simulation and visualization of the robot -->
    
		<!-- <transmission name="${prefix}_wheel_trans" type="SimpleTransmission">
      			<type>transmission_interface/SimpleTransmission</type>
      			<actuator name="${prefix}_wheel_motor">
        			<mechanicalReduction>1</mechanicalReduction>
      			</actuator>
      	
			<joint name="${prefix}_wheel_joint">
        			<hardwareInterface>VelocityJointInterface</hardwareInterface>
      			</joint>
		</transmission>-->
	</xacro:macro>
	<xacro:wheel prefix="right" reflect="1" />
	<xacro:wheel prefix="left" reflect="-1" />

</robot>

